### ISSUE TITLE
Does MILC Scale to MultiNode MultiGPU

### ISSUE THREAD

**Issue by saipavan27** [milc-qcd/milc_qcd#38]
I want to try MILC on MultiNode MultiGPU setup. Does it scale to this?

**Comment by stevengottlieb** [comment]
Yes, it does.  You should look at the instructions for compiling QUDA on GitHub.  When compiling MILC make sure to set MPP and WANTQUDA to be true.

Hope this helps,
Steven Gottlieb

On Jul 17, 2020, at 1:19 AM, saipavan27 <notifications@github.com<mailto:notifications@github.com>> wrote:



I want to try MILC on MultiNode MultiGPU setup. Does it scale to this?

**Comment by saipavan27** [comment]
Thanks!
