### ISSUE TITLE
Inquiry Regarding ARM64 Architecture Support for MILC Application

### ISSUE THREAD

**Issue by Masterwater-y** [milc-qcd/milc_qcd#63]
I am encountering challenges while attempting to compile ks_imp_rhmc on a machine with the ARM64 architecture. 

Below is the error messages, it seems the libraries don't support arm64
`/usr/bin/ld: ../libraries/su3.2.a(cs_m_a_mat.2.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../libraries/su3.2.a(cs_m_a_mat.2.o): Relocations in generic ELF (EM: 62)
/usr/bin/ld: ../libraries/su3.2.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[1]: *** [Make_template:388: localmake] Error 1`

The Makefile works at x86-64 machine
[Makefile_198.txt](https://github.com/milc-qcd/milc_qcd/files/13442054/Makefile_198.txt)

**Comment by stevengottlieb** [comment]
Did you compile the library files for ARM64?  That is, did you

make -f Make_vanilla clean
make -f Make_vanilla all

Steven Gottlieb

On Nov 22, 2023, at 11:24 AM, Masterwater-y ***@***.***> wrote:



I am encountering challenges while attempting to compile ks_imp_rhmc on a machine with the ARM64 architecture.

Below is the error messages, it seems the libraries don't support arm64
/usr/bin/ld: ../libraries/su3.2.a(cs_m_a_mat.2.o): Relocations in generic ELF (EM: 62) /usr/bin/ld: ../libraries/su3.2.a(cs_m_a_mat.2.o): Relocations in generic ELF (EM: 62) /usr/bin/ld: ../libraries/su3.2.a: error adding symbols: file in wrong format collect2: error: ld returned 1 exit status make[1]: *** [Make_template:388: localmake] Error 1

The Makefile
Makefile_198.txt<https://github.com/milc-qcd/milc_qcd/files/13442054/Makefile_198.txt>

**Comment by Masterwater-y** [comment]
It works, thank you very much
